Don't use hardcoded path in initialization

diff --git a/fzmake/scripts/nightlygen b/fzmake/scripts/nightlygen
--- a/fzmake/scripts/nightlygen
+++ b/fzmake/scripts/nightlygen
@@ -2,7 +2,18 @@
 
 . /etc/profile
 
-cd /home/nightlybuild/scripts
+function init()
+{
+  local dir=${0%/*}
+  if [ ! -f "$dir/config" ]; then
+    echo "Can't find master config. Aborting"
+    exit 1
+  fi
+  cd "$dir"
+  return 0
+}
+
+init || exit 1
 
 . config
 . log.sh
